import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: "404 - Page not found",
  description: "Generated by create next app",
};

export default function GlobalNotFound() {
    return (
        <html lang="en">
            <body>
                <h1>404 - Page not found</h1>
            </body>
        </html>
    );
}